name: Test devcontainer

on:
  pull_request:
    paths:
      - "src/**"
      - ".github/workflows/build-image.yml"
      - ".github/workflows/test.yml"
      - ".github/workflows/prepare.yml"
      - ".github/splunk-versions.json"
  workflow_dispatch:
    inputs:
      all_versions:
        description: "Build all versions, including inactive"
        type: boolean
        default: false

concurrency:
  group: test-${{ github.ref }}
  cancel-in-progress: true

permissions:
  contents: read

jobs:
  versions:
    uses: ./.github/workflows/prepare.yml
    with:
      image_tag: v0.0.0
      all_versions: ${{ inputs.all_versions || false }}

  build:
    needs: versions
    uses: ./.github/workflows/build-image.yml
    with:
      image_version: ${{ needs.versions.outputs.image_version }}
      image_major: ${{ needs.versions.outputs.image_major }}
      image_minor: ${{ needs.versions.outputs.image_minor }}
      splunk_latest: ${{ needs.versions.outputs.splunk_latest }}
      splunk_major: ${{ needs.versions.outputs.splunk_major }}
      splunk_minor: ${{ needs.versions.outputs.splunk_minor }}
      all_versions: ${{ inputs.all_versions || false }}
