name: Test 9.4.6 Only

on:
  workflow_dispatch: # Manual trigger only

jobs:
  test-splunk-946:
    runs-on: ubuntu-latest

    strategy:
      fail-fast: false
      matrix:
        version: [9.4.5, 9.4.6]
        variant: [splunk, universalforwarder]
        include:
          - version: 9.4.5
            build: "60284236e579" # test with 9.4.6 build hash
            platform: linux-amd64
          - version: 9.4.6
            build: 60284236e579
            platform: linux-amd64

    steps:
      - name: Display matrix values
        run: |
          echo "Variant: ${{ matrix.variant }}"
          echo "Version: ${{ matrix.version }}"
          echo "Build: ${{ matrix.build }}"
          echo "Platform: ${{ matrix.platform }}"
